# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kai Krüger
title_seperator: "|"

name: "Kai Krüger"
email: kai.krueger@bibb.de
description: >- # this means to ignore newlines until "baseurl:"
  Personal website an blog of Kai Krüger, researcher in computational linguistics. 
# twitter_username: username
github_username: kruegerETRF
url: "https://kruegeretrf.github.io"
#baseurl: kruegeretrf
repository: "kruegeretrf/kruegeretrf.github.io"
minimal_mistakes_skin: air
search: true


# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin


#masterhead
logo: "/assets/images/masterhead_logo.png"
masthead_title: "Home"



include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Kai Krüger"
  avatar : "/assets/images/bio-pic.jpg"
  bio    : "Computational Linguist at [BIBB](https://www.bibb.de/en/index.php). I blog about all things NLP, AI and Cognitive Linguistics."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/KruegerETRF/"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kai-kr%C3%BCger-494773163/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/kaikrueger.1/"

footer:
  links:
      - label: "GitHub"
        icon: "fab fa-fw fa-github"
        url: "https://github.com/KruegerETRF/"
      - label: "LinkedIn"
        icon: "fab fa-fw fa-linkedin"
        url: "https://www.linkedin.com/in/kai-kr%C3%BCger-494773163/"
      - label: "Instagram"
        icon: "fab fa-fw fa-instagram"
        url: "https://www.instagram.com/kaikrueger.1/"


teaser: /assets/images/default_teaser.png
og_image: /assets/images/masterhead_logo.png


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      date_format: "%Y-%m-%d"

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

og_image: /assets/images/masterhead_logo.png

social:
  type:  Person
  name:  Kai Krüger
  links:
    - "https://www.instagram.com/kaikrueger.1/"
    - "https://www.linkedin.com/in/kai-kr%C3%BCger-494773163/"


compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment
